import { routes } from './routes';

export const pageTitles = {
  [routes.main]: 'app.title.main',
  [routes.trainings]: 'app.title.trainings',
  [routes.mealPlan]: 'app.title.meal_plan',
  [routes.nutritionPlanWeight]: 'app.title.goals',
  [routes.shoppingList]: 'app.title.shopping_list',
  [routes.createRecipe]: 'app.title.recipe_create',
  [routes.mealPlanList]: 'app.title.meal_plan',
  [routes.recipes]: 'app.title.recipes',
  [routes.waterTracker]: 'app.title.water_tracker',
  [routes.changeMealSettings]: 'app.title.change_meal_plan',
  [routes.personalSettings]: 'app.title.settings_personal',
  [routes.favouritesRecipes]: 'app.title.favourite_recipes',
  [routes.faqSettings]: 'app.title.faq',
  [routes.referral]: 'app.title.referral',
  [routes.familySettings]: 'app.title.family',
  [routes.addTestimonial]: 'app.title.testimonials',
  [routes.cancellation]: 'app.title.cancellation',
  [routes.login]: 'app.title.login',
  [routes.register]: 'app.title.register',
  [routes.resetPasword]: 'app.title.reset_password',
  [routes.saveNewPasword]: 'app.title.reset_password.new',
  [routes.recipeFullView]: 'app.title.recipe',
  [routes.registerWelcome]: 'app.title.after_signup',
  [routes.checkout]: 'app.title.checkout',
  [routes.checkoutThankyou]: 'app.title.after_checkout',
  [routes.paymentHistorySettings]: 'app.title.payment.history',
  [routes.subscriptionPlanSettings]: 'app.title.subscription',
  [routes.joinFamily]: 'app.title.join_family',
};
