export const routes = {
  main: '/',
  trainings: '/trainings',
  mealPlan: '/meal-plan',
  nutritionPlanWeight: '/nutrition/plan/weights',
  shoppingList: '/shopping-list',
  createRecipe: '/recipe/create',
  mealPlanList: '/meal-plan/list',
  recipes: '/recipes',
  waterTracker: '/water-tracker',
  changeMealSettings: '/settings/change-meal-plan',
  personalSettings: '/settings/personal',
  savedRecipes: '/recipes/saved',
  favouritesRecipes: '/recipes/favourites',
  dashboard: '/dashboard',
  faqSettings: '/settings/faq',
  referral: '/referral',
  familySettings: '/settings/family',
  addTestimonial: '/add_testimonial',
  cancellation: '/cancellation',
  login: '/login',
  register: '/register',
  recipeFullView: '/recipe/:recipeId',
  afterSignup: '/after-signup',
  checkout: '/checkout',
  getRecipeFullView: (recipeId: string) => `/recipe/${recipeId}`,
  paymentHistorySettings: '/settings/payment-history',
};
