export const routes = {
  main: '/',
  trainings: '/trainings',
  nutritionPlan: '/nutrition/plan',
  nutritionPlanWeight: '/nutrition/plan/weights',
  shoppingList: '/shopping-list',
  createRecipe: '/recipe/create',
  mealPlanList: '/meal-plan/list',
  recipes: '/recipes',
  waterTracker: '/water-tracker',
  changeMeal: '/plan/change-meal',
  personalSettings: '/settings/personal',
  savedRecipes: '/recipes/saved',
  favouritesRecipes: '/recipes/favourites',
  dashboard: '/dashboard',
  faqSettings: '/settings/faq',
  referral: '/referral',
  familySettings: '/settings/family',
  addTestimonial: '/add_testimonial',
  cancellation: '/cancellation',
  login: '/login',
  register: '/register',
  recipeFullView: '/recipe/:recipeId',
};
