import NutritionPlanPreviewImage from 'assets/img/nutrition-plan-preview-img.jpg';
import { ReactComponent as BreakfastIcon } from 'assets/img/icons/breakfast-icon.svg';
import { ReactComponent as LunchIcon } from 'assets/img/icons/lunch-icon.svg';
import { ReactComponent as SnackIcon } from 'assets/img/icons/snack-icon.svg';
import { ReactComponent as DinnerIcon } from 'assets/img/icons/dinner-icon.svg';

export const weeks = [
  {
    title: '12.07.2020-18.07.2020',
    days: [
      {
        date: 'Monday, July 12nd',
        number: '12',
        value: 'mon',
        mealPlan: [
          {
            title: 'Breakfast',
            icon: BreakfastIcon,
            // type: 'active',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: LunchIcon,
            // type: 'cross',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: SnackIcon,
            // type: 'default',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Dinner',
            icon: DinnerIcon,
            // type: 'active',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
        ],
      },
      {
        date: 'Tuesday, July 13nd',
        number: '13',
        value: 'tus',
        mealPlan: [
          {
            title: 'Breakfast',
            icon: BreakfastIcon,
            // type: 'active',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: LunchIcon,
            // type: 'cross',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: SnackIcon,
            // type: 'default',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Dinner',
            icon: DinnerIcon,
            // type: 'active',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
        ],
      },
      {
        date: 'Wednesday, July 14nd',
        number: '14',
        value: 'wed',
        mealPlan: [
          {
            title: 'Breakfast',
            icon: BreakfastIcon,
            // type: 'active',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: LunchIcon,
            // type: 'cross',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: SnackIcon,
            // type: 'default',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Dinner',
            icon: DinnerIcon,
            // type: 'active',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
        ],
      },
      {
        date: 'Thursday, July 15nd',
        number: '15',
        value: 'thu',
        mealPlan: [
          {
            title: 'Breakfast',
            icon: BreakfastIcon,
            // type: 'active',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: LunchIcon,
            // type: 'cross',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: SnackIcon,
            // type: 'default',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Dinner',
            icon: DinnerIcon,
            // type: 'active',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
        ],
      },
      {
        date: 'Friday, July 16nd',
        number: '16',
        value: 'fri',
        mealPlan: [
          {
            title: 'Breakfast',
            icon: BreakfastIcon,
            // type: 'active',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: LunchIcon,
            // type: 'cross',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: SnackIcon,
            // type: 'default',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Dinner',
            icon: DinnerIcon,
            // type: 'active',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
        ],
      },
      {
        date: 'Saturday, July 17nd',
        number: '17',
        value: 'sat',
        mealPlan: [
          {
            title: 'Breakfast',
            icon: BreakfastIcon,
            // type: 'active',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: LunchIcon,
            // type: 'cross',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: SnackIcon,
            // type: 'default',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Dinner',
            icon: DinnerIcon,
            // type: 'active',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
        ],
      },
      {
        date: 'Sunday, July 18nd',
        number: '18',
        value: 'sun',
        mealPlan: [
          {
            title: 'Breakfast',
            icon: BreakfastIcon,
            // type: 'active',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: LunchIcon,
            // type: 'cross',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: SnackIcon,
            // type: 'default',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Dinner',
            icon: DinnerIcon,
            // type: 'active',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
        ],
      },
    ],
  },
  {
    title: '19.07.2020-25.07.2020',
    days: [
      {
        date: 'Monday, July 19nd',
        number: '19',
        value: 'mon',
        mealPlan: [
          {
            title: 'Breakfast',
            icon: BreakfastIcon,
            // type: 'active',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: LunchIcon,
            // type: 'cross',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: SnackIcon,
            // type: 'default',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Dinner',
            icon: DinnerIcon,
            // type: 'active',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
        ],
      },
      {
        date: 'Tuesday, July 20nd',
        number: '20',
        value: 'tus',
        mealPlan: [
          {
            title: 'Breakfast',
            icon: BreakfastIcon,
            // type: 'active',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: LunchIcon,
            // type: 'cross',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: SnackIcon,
            // type: 'default',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Dinner',
            icon: DinnerIcon,
            // type: 'active',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
        ],
      },
      {
        date: 'Wednesday, July 21nd',
        number: '21',
        value: 'wed',
        mealPlan: [
          {
            title: 'Breakfast',
            icon: BreakfastIcon,
            // type: 'active',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: LunchIcon,
            // type: 'cross',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: SnackIcon,
            // type: 'default',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Dinner',
            icon: DinnerIcon,
            // type: 'active',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
        ],
      },
      {
        date: 'Thursday, July 22nd',
        number: '22',
        value: 'thu',
        mealPlan: [
          {
            title: 'Breakfast',
            icon: BreakfastIcon,
            // type: 'active',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: LunchIcon,
            // type: 'cross',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: SnackIcon,
            // type: 'default',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Dinner',
            icon: DinnerIcon,
            // type: 'active',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
        ],
      },
      {
        date: 'Friday, July 23nd',
        number: '23',
        value: 'fri',
        mealPlan: [
          {
            title: 'Breakfast',
            icon: BreakfastIcon,
            // type: 'active',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: LunchIcon,
            // type: 'cross',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: SnackIcon,
            // type: 'default',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Dinner',
            icon: DinnerIcon,
            // type: 'active',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
        ],
      },
      {
        date: 'Saturday, July 24nd',
        number: '24',
        value: 'sat',
        mealPlan: [
          {
            title: 'Breakfast',
            icon: BreakfastIcon,
            // type: 'active',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: LunchIcon,
            // type: 'cross',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: SnackIcon,
            // type: 'default',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Dinner',
            icon: DinnerIcon,
            // type: 'active',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
        ],
      },
      {
        date: 'Sunday, July 25nd',
        number: '25',
        value: 'sun',
        mealPlan: [
          {
            title: 'Breakfast',
            icon: BreakfastIcon,
            // type: 'active',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: LunchIcon,
            // type: 'cross',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Snack',
            icon: SnackIcon,
            // type: 'default',
            favorite: true,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
          {
            title: 'Dinner',
            icon: DinnerIcon,
            // type: 'active',
            favorite: false,
            image: NutritionPlanPreviewImage,
            desc: 'Õuna-rosina kohupiimavorm',
            time: '40 min',
            price: '€€',
          },
        ],
      },
    ],
  },
];
